apiVersion: v1
kind: Service
metadata:
  name: {{ include "terra-super-echo.fullname" . }}-webui
  labels:
    {{- include "terra-super-echo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webui.service.type }}
  ports:
    - port: {{ .Values.webui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "terra-super-echo.selectorLabels" . | nindent 4 }}
    app: webui
