apiVersion: v1
kind: Service
metadata:
  name: {{ include "terra-super-echo.fullname" . }}-yodeler
  labels:
    {{- include "terra-super-echo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.yodeler.service.type }}
  ports:
    - port: {{ .Values.yodeler.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "terra-super-echo.selectorLabels" . | nindent 4 }}
    app: yodeler
